/**
 * Canonical English/Bangla label dictionaries for prescription section headers,
 * vitals rows, and the patient-info block — mirrors the reference prototype's
 * `src/data/prescriptionLabels.js` (LABELS_EN/LABELS_BN/defaultLabelsForLanguage),
 * using this codebase's own key names where they diverged (e.g. `vitalRespiratoryRate`
 * instead of the prototype's `vitalRespRate`).
 *
 * A template's own `config.labels` only ever held partial/English overrides, so without
 * this, every static label (section headers, patient-info field names) stayed in English
 * even when the doctor switched the prescription to বাংলা — only doctor-typed free text
 * (via the Avro phonetic directive) actually changed language. `resolveLabels` fixes that
 * by picking the base dictionary from the *currently selected* language first, then
 * layering the template's own overrides on top.
 */
export const LABELS_EN: Record<string, string> = {
  patientName: 'Name',
  patientAge: 'Age',
  patientSex: 'Sex',
  patientPhone: 'Phone',
  patientBloodGroup: 'Blood Group',
  patientAllergies: 'Allergies',
  patientDate: 'Date',
  patientRxNo: 'Rx No',

  chiefComplaint: 'C/C',
  history: 'H/O',
  examination: 'O/E',
  diagnosis: 'Dx',
  investigation: 'Inv',
  prescriptionHeading: 'Rx',
  advice: 'Advice',
  followUp: 'Follow-Up',
  doctorSignature: "Doctor's Signature",
  chiefComplaintPlaceholder: 'Fever for 3 days',
  historyPlaceholder: 'DM x 5 years',
  investigationPlaceholder: 'CBC',
  advicePlaceholder: 'Write advice here...',
  followUpPlaceholder: 'e.g. Review after 7 days',
  followUpEmpty: 'Not specified.',
  ccAddPlaceholder: 'Add complaint...',
  historyAddPlaceholder: 'Add history...',
  investigationAddPlaceholder: 'Add investigation...',
  adviceAddPlaceholder: 'Add advice...',
  medEmptyReadonly: 'No medicines prescribed.',
  medEmptyEditable: 'No medicines added yet.',
  medSearchPlaceholder: 'Medicine name',
  medStrengthPlaceholder: 'Strength',
  medDosage: 'Dosage',
  medFrequency: 'Frequency',
  medDuration: 'Duration',
  medInstructions: 'Instructions',

  vitalBP: 'BP',
  vitalPulse: 'Pulse',
  vitalTempEditable: 'Temp (°F)',
  vitalWeightEditable: 'Weight (kg)',
  vitalHeightEditable: 'Height (cm)',
  vitalBMI: 'BMI',
  vitalRespiratoryRate: 'Resp. Rate',
  vitalSpo2: 'SpO2 (%)',
  vitalBloodSugar: 'Blood Sugar',
  vitalPainScore: 'Pain Score',
  vitalHeartRate: 'Heart Rate',

  regNo: 'Reg No',
  bmdcRegNo: 'BM&DC Reg. No',
  callPrefix: 'Call',
  emergency: 'Emergency',
  generatedBy: 'Generated by PrescriptionMS',
  qrScanToVerify: 'Scan to verify',
};

export const LABELS_BN: Record<string, string> = {
  patientName: 'নাম',
  patientAge: 'বয়স',
  patientSex: 'লিঙ্গ',
  patientPhone: 'ফোন',
  patientBloodGroup: 'রক্তের গ্রুপ',
  patientAllergies: 'অ্যালার্জি',
  patientDate: 'তারিখ',
  patientRxNo: 'প্রেসক্রিপশন নং',

  chiefComplaint: 'প্রধান অভিযোগ',
  history: 'রোগের ইতিহাস',
  examination: 'শারীরিক পরীক্ষা',
  diagnosis: 'রোগ নির্ণয়',
  investigation: 'পরীক্ষা',
  prescriptionHeading: 'Rx',
  advice: 'পরামর্শ',
  followUp: 'পরবর্তী সাক্ষাৎ',
  doctorSignature: 'চিকিৎসকের স্বাক্ষর',
  chiefComplaintPlaceholder: 'যেমন: ৩ দিন ধরে জ্বর',
  historyPlaceholder: 'যেমন: ৫ বছর ধরে ডায়াবেটিস',
  investigationPlaceholder: 'সিবিসি',
  advicePlaceholder: 'পরামর্শ লিখুন...',
  followUpPlaceholder: 'যেমন: ৭ দিন পর আবার দেখান',
  followUpEmpty: 'উল্লেখ নেই।',
  ccAddPlaceholder: 'অভিযোগ যোগ করুন...',
  historyAddPlaceholder: 'ইতিহাস যোগ করুন...',
  investigationAddPlaceholder: 'পরীক্ষা যোগ করুন...',
  adviceAddPlaceholder: 'পরামর্শ যোগ করুন...',
  medEmptyReadonly: 'কোনো ওষুধ নির্ধারিত হয়নি।',
  medEmptyEditable: 'এখনও কোনো ওষুধ যোগ করা হয়নি।',
  medSearchPlaceholder: 'ওষুধ',
  medStrengthPlaceholder: 'শক্তি',
  medDosage: 'মাত্রা',
  medFrequency: 'সেবনবিধি',
  medDuration: 'মেয়াদ',
  medInstructions: 'নির্দেশনা',

  vitalBP: 'রক্তচাপ',
  vitalPulse: 'নাড়ি',
  vitalTempEditable: 'তাপমাত্রা (°ফা)',
  vitalWeightEditable: 'ওজন (কেজি)',
  vitalHeightEditable: 'উচ্চতা (সেমি)',
  vitalBMI: 'বিএমআই',
  vitalRespiratoryRate: 'শ্বাসের হার',
  vitalSpo2: 'এসপিও২ (%)',
  vitalBloodSugar: 'রক্তে শর্করা',
  vitalPainScore: 'ব্যথার মাত্রা',
  vitalHeartRate: 'হৃদস্পন্দন',

  regNo: 'নিবন্ধন নং',
  bmdcRegNo: 'বিএমএন্ডিসি নিবন্ধন নং',
  callPrefix: 'কল',
  emergency: 'জরুরি',
  generatedBy: 'PrescriptionMS দ্বারা তৈরি',
  qrScanToVerify: 'যাচাই করতে স্ক্যান করুন',
};

/**
 * Labels for the doctor's currently-selected language.
 *
 * The base EN/BN dictionary WINS over the template's stored `config.labels`. This is a
 * deliberate inversion of the usual "overrides on top" merge, forced by how the backend
 * seeds templates (Application/Features/Templates/TemplateDefaults.cs): every template is
 * created with a *fully-populated* label dictionary in its own authored language, so an
 * English-authored template carries a complete set of English strings. If those were
 * allowed to override, switching the prescription to বাংলা at runtime would leave every
 * static label in English (only doctor-typed free text would change) — exactly the bug
 * this fixes. The backend's Bangla dictionary also keeps the clinical section headers
 * (C/C, H/O, O/E, Dx, Inv) in English, so honoring it wouldn't help even for a
 * Bangla-authored template. Driving purely from these prototype-accurate dictionaries,
 * keyed by the runtime language, is what makes bn → all-Bangla and en → all-English.
 *
 * Trade-off: genuine per-template label customizations made via the Template Editor no
 * longer affect these rendered labels (they're still stored, just not applied here).
 * `config.labels` is kept only as a last-resort fallback for any key the base dictionary
 * doesn't define.
 */
export function resolveLabels(language: 'en' | 'bn', overrides?: Record<string, string> | null): Record<string, string> {
  const base = language === 'bn' ? LABELS_BN : LABELS_EN;
  return overrides ? { ...overrides, ...base } : { ...base };
}
